export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const REGISTER = "REGISTER"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"

export const FETCH_CONTACT = "FETCH_CONTACT"
export const FETCH_CONTACT_SUCCESSFUL = "FETCH_CONTACT_SUCCESSFUL"
export const FETCH_CONTACT_FAILED = "FETCH_CONTACT_FAILED"


export const ADD_CONTACT = "ADD_CONTACT"
export const ADD_CONTACT_SUCCESSFUL = "ADD_CONTACT_SUCCESSFUL"
export const ADD_CONTACT_FAILED = "ADD_CONTACT_FAILED"


export const UPDATE_CONTACT = "UPDATE_CONTACT"
export const UPDATE_CONTACT_SUCCESSFUL = "UPDATE_CONTACT_SUCCESSFUL"
export const UPDATE_CONTACT_FAILED = "UPDATE_CONTACT_FAILED"


export const DELETE_CONTACT = "DELETE_CONTACT"
export const DELETE_CONTACT_SUCCESSFUL = "DELETE_CONTACT_SUCCESSFUL"
export const DELETE_CONTACT_FAILED = "DELETE_CONTACT_FAILED"


export const FETCH_USER = "FETCH_USER"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_FAILED = "FETCH_USER_FAILED"

export const SEND_MAIL_SUCCESS = "SEND_MAIL_SUCCESS"
export const SEND_MAIL_FAILED = "SEND_MAIL_FAILED"

export const CONTACT_DETAIL_SUCCESS = "CONTACT_DETAIL_SUCCESS"
export const CONTACT_DETAIL_FAILED = "CONTACT_DETAIL_FAILED"

export const SEARCH = "SEARCH"

export const USER_AVATAR_SUCCESS = "USER_AVATAR_SUCCESS"
export const USER_AVATAR_FAILED = "USER_AVATAR_FAILED"

export const CONTACT_AVATAR_FAILED = "CONTACT_AVATAR_FAILED"
export const CONTACT_AVATAR_SUCCESS = "CONTACT_AVATAR_SUCCESS"